import appleLogo from "../assets/apple.svg";
import colabLogo from "../assets/colab-logo.svg";

export const applicationHistory = [
  {
    id: 0,
    companyLogo: colabLogo,
    jobTitle: "Data Science Internship - 2024",
    companyName: "Colab Innovation Hub",
    location: "Kaduna,NG",
    category: "remote",
    type: "Full time",
    dateApplied: "10-01-2024",
    status: "pending",
  },
  {
    id: 1,
    companyLogo: colabLogo,
    jobTitle: "Data Science Internship - 2024",
    companyName: "Colab Innovation Hub",
    location: "Kaduna,NG",
    category: "remote",
    type: "Full time",
    dateApplied: "10-01-2024",
    status: "pending",
  },
  {
    id: 2,
    companyLogo: colabLogo,
    jobTitle: "Data Science Internship - 2024",
    companyName: "Colab Innovation Hub",
    location: "Kaduna,NG",
    category: "remote",
    type: "Full time",
    dateApplied: "10-01-2024",
    status: "accepted",
  },
  {
    id: 3,
    companyLogo: colabLogo,
    jobTitle: "Data Science Internship - 2024",
    companyName: "Colab Innovation Hub",
    location: "Kaduna,NG",
    category: "remote",
    type: "Full time",
    dateApplied: "10-01-2024",
    status: "pending",
  },
  {
    id: 4,
    companyLogo: colabLogo,
    jobTitle: "Data Science Internship - 2024",
    companyName: "Colab Innovation Hub",
    location: "Kaduna,NG",
    category: "remote",
    type: "Full time",
    dateApplied: "10-01-2024",
    status: "pending",
  },
  {
    id: 5,
    companyLogo: colabLogo,
    jobTitle: "Data Science Internship - 2024",
    companyName: "Colab Innovation Hub",
    location: "Kaduna,NG",
    category: "remote",
    type: "Full time",
    dateApplied: "10-01-2024",
    status: "pending",
  },
  {
    id: 6,
    companyLogo: colabLogo,
    jobTitle: "Data Science Internship - 2024",
    companyName: "Colab Innovation Hub",
    location: "Kaduna,NG",
    category: "remote",
    type: "Full time",
    dateApplied: "10-01-2024",
    status: "declined",
  },
  {
    id: 7,
    companyLogo: colabLogo,
    jobTitle: "Data Science Internship - 2024",
    companyName: "Colab Innovation Hub",
    location: "Kaduna,NG",
    category: "remote",
    type: "Full time",
    dateApplied: "10-01-2024",
    status: "pending",
  },
];
